name: Dockerhub CI

on:
  workflow_dispatch:

jobs:
  convert1:
    runs-on: ubuntu-20.04
    environment: vconvert
    steps:
      - uses: docker-practice/actions-setup-docker@master
        with:
          docker_channel: nightly
          # this value please see https://github.com/AkihiroSuda/moby-snapshot/releases
          docker_nightly_version: snapshot-20201109
      -
        name: Checkout
        uses: actions/checkout@v2
      - name: Run Dockerfile
        run: |
          docker build -t vconvert .
          docker run -it  -e "log_level=debug" -e "remove_origin=false" -e "mode=both" -e "sleep_time=3600" -e "threads=2" \
          -e "format=mp4" -e "vc=h265" -e "ac=aac" -e "bit=10" -e "fb_api_key={{ secrets.FB_API_KEY }}" \
          -e "fb_project_id={{ secrets.FB_PROJECT_ID }}" -e "fb_db_url={{ secrets.FB_DB_URL }}" -e "fb_email={{ secrets.FB_EMAIL }}" \
          -e "fb_password={{ secrets.FB_PASSWORD }}" -e "CLIENT_ID={{ secrets.CLIENT_ID }}" -e "CLIENT_SECRET={{ secrets.CLIENT_SECRET }}" \
          -e "TOKEN={{ secrets.TOKEN }}" -e "TEAM_DRIVE={{ secrets.TEAM_DRIVE }}" -e "ROOT_FOLDER={{ secrets.ROOT_FOLDER }}" \
          -v /mnt/gdrive:/vconvert vconvert