name: vconvert

on:
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-20.04
    environment: vconvert
    strategy:
      matrix:
        sleep_time: ["10s", "20s", "30s", "40s", "50s", "60s", "70s", "80s", "90s", "100s", "110s", "120s", "130s", "140s", "150s", "160s", "170s", "180s", "190s", 200s"]
      fail-fast: false
    steps:
      - name: Sleep
        uses: jakejarvis/wait-action@master
        with:
          time: ${{ matrix.sleep_time }}
      - uses: docker-practice/actions-setup-docker@master
        with:
          docker_channel: stable
          docker_version: "20.10"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          docker build -t vconvert \
          --build-arg CLIENT_ID=${{ secrets.CLIENT_ID }} --build-arg CLIENT_SECRET=${{ secrets.CLIENT_SECRET }} \
          --build-arg TOKEN='${{ secrets.TOKEN }}' --build-arg TEAM_DRIVE=${{ secrets.TEAM_DRIVE }} \
          --build-arg ROOT_FOLDER=${{ secrets.ROOT_FOLDER }} .
      - name: RUN
        run: |
          docker run --rm --device /dev/fuse --cap-add SYS_ADMIN --security-opt apparmor:unconfined \
          -e "log_level=${{ secrets.LOG_LEVEL }}" -e "remove_origin=${{ secrets.RM_ORIGIN }}" -e "mode=${{ secrets.MODE }}" \
          -e "threads=2" -e "format=${{ secrets.FORMAT }}" -e "vc=${{ secrets.VC_FORMAT }}" -e "ac=${{ secrets.AC_FORMAT }}" \
          -e "bit=${{ secrets.VC_BIT }}" -e "crf=${{ secrets.VC_CRF }}" -e "force_convert=${{ secrets.FORCE_CONVERT }}" \
          -e "fb_api_key=${{ secrets.FB_API_KEY }}" -e "fb_project_id=${{ secrets.FB_PROJECT_ID }}" -e "fb_db_url=${{ secrets.FB_DB_URL }}" \
          -e "fb_email=${{ secrets.FB_EMAIL }}" -e "fb_password=${{ secrets.FB_PASSWORD }}" -e "sleep_time=${{ secrets.SLEEP_TIME }}" \
          vconvert