name: vconvert

on:
  workflow_dispatch:

jobs:
  convert1:
    runs-on: ubuntu-20.04
    environment: vconvert
    steps:
      - uses: docker-practice/actions-setup-docker@master
        with:
          docker_channel: nightly
          # this value please see https://github.com/AkihiroSuda/moby-snapshot/releases
          docker_nightly_version: snapshot-20201109
      -
        name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          docker build -t vconvert \
          --build-arg CLIENT_ID=${{ secrets.CLIENT_ID }} --build-arg CLIENT_SECRET=${{ secrets.CLIENT_SECRET }} \
          --build-arg TOKEN='${{ secrets.TOKEN }}' --build-arg TEAM_DRIVE=${{ secrets.TEAM_DRIVE }} \
          --build-arg ROOT_FOLDER=${{ secrets.ROOT_FOLDER }} .
      - name: RUN
        run: |
          docker run --rm --device /dev/fuse --cap-add SYS_ADMIN --security-opt apparmor:unconfined \
          -e "log_level=${{ secrets.LOG_LEVEL }}" -e "remove_origin=${{ secrets.RM_ORIGIN }}" -e "mode=${{ secrets.MODE }}" \
          -e "threads=2" -e "format=${{ secrets.FORMAT }}" -e "vc=${{ secrets.VC_FORMAT }}" -e "ac=${{ secrets.AC_FORMAT }}" -e "bit=${{ secrets.VC_BIT }}" \
          -e "fb_api_key=${{ secrets.FB_API_KEY }}" -e "fb_project_id=${{ secrets.FB_PROJECT_ID }}" -e "fb_db_url=${{ secrets.FB_DB_URL }}" \
          -e "fb_email=${{ secrets.FB_EMAIL }}" -e "fb_password=${{ secrets.FB_PASSWORD }}" -e "sleep_time=${{ secrets.SLEEP_TIME }}" \
          -e "force_convert=${{ secrets.FORCE_CONVERT }}" vconvert
